### ISSUE TITLE
Définition du projet

### ISSUE THREAD

**Issue by sanderator** [mundus-2018-19/zifanxu#1]
J'ai un sujet potentiel. Ce n'est pas très IOT car il nous manque le Thing. J'ai un Arduino chez moi, et un nombre de projets en tête, mais il faudrait certainement commander du matériel, et le temps de le faire manque.
Donc, j'ai pensé à : une simulation de la saturation / désaturation en gaz (azote) d'un tissu de plongeur sous-marin en fonction du profil de la plongée. Ensuite, on modélise un plongeur par différents tissus de caractéristiques spécifiques (tissus lents, tissus rapides) pour déterminer quel tissu limite la vitesse de remontée, et quel nécessite d'éventuels paliers de décompression afin d'éviter un accident de décompression.
Ensuite, avec des outils graphiques, on pourrait contrôler interactivement les paramétres de plongée (temps, profondeurs) pour voir en temps réel comment les tissus réagissent.
Ce type de modèle déterministe est à la base des _ordinateurs_ de plongée. Cependant, les _tables_ modernes de plongée sont plutôt détermineées à partir d'analyses statistiques de beaucoup beaucoup beaucoup de profils de plongées réelles. Si on pouvait trouver quelque part une base de données publique de ces profils, on pourrait comparer le modèle déterministe aux données statistiques. Ou peut-être il suffirait simplement de faire une comparison plus simple ordinateur / tables.
Et, bien sûr, il y différents théories de la (dé)saturation : 
[https://en.wikipedia.org/wiki/History_of_decompression_research_and_development]

**Comment by SebAsuka** [comment]
Je pense que ça peut être un très bon sujet qui pourra m'aider beaucoup. Si j'ai bien compris, le produit fini sera un simulateur avec des paramètres interactives. On change des paramètres et voit comment les résultats réagissent

**Comment by sanderator** [comment]
Exacte ! J'avais fait un outil comme ça dans un passé lointain et cela m'a beaucoup aider à comprendre ce qui se passait sous l'eau. Hélas, je ne trouve plus l'application. Mais ça serait bien de la refaire en mieux avec des outils modernes.

**Comment by SebAsuka** [comment]
Pour moi JavaScript et Java sont OK, mais Python il faut commencer à partir de zero. En fait je n'ai pas d'idée laquelle parmi les trois langues sera mieux pour mois et pour ce projet.

**Comment by sanderator** [comment]
A mon avis, c'est JavaScript / Vue qui seraient le plus adaptés au projet. On peut appliquer les bons principes de la POO aussi bien à JS qu'à Java.
S'il le faut, on peut aussi travailler le Java à côté du projet, pour ne pas l'oublier.

**Comment by SebAsuka** [comment]
OK ! Je me réjuis de pouvoir le faire !
